apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-name
spec:
  storageClassName: manual
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # This was added after learning about the abstraction called StorageClass,
  # which is just a few minutes after everything else in this directory tbh.
  storageClassName: storage-class-name